# Site settings
title: Lachlan Holland Blog
email: 
description: "Welcome to my blog."
baseurl: ""
url: "http://lachlanholland1.github.io"
github_username:  lachlanholland1

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge