# Site settings
title: Lachlan Holland Blog
email: 
description: "Hi, I'm Lachlan. Welcome to my blog!"
baseurl: ""
url: "https://lachlanholland.com"
github_username:  lachlanholland1

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge